import { Announcement, Event, Notification, Registration, User } from '../types';

export const mockUser: User = {
    id: '1',
    email: 'student@college.edu',
    name: 'John Doe',
    rollNumber: 'CS2023001',
    role: 'student',
};

export const mockEvents: Event[] = [
    {
        id: '1',
        name: 'Tech-Nexus Hackathon',
        club: 'Coding Club',
        clubId: 'c1',
        description: 'A 48-hour challenge to build innovative solutions for sustainable living. Show your skills in web, mobile, or AI!',
        rules: '1. Teams of 2-4 members.\n2. Original code only.\n3. Bring your own hardware.',
        venue: 'Advanced Computing Lab',
        date: '2026-03-15T09:00:00Z',
        deadline: '2026-03-10T23:59:59Z',
        poster: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80',
        isClosed: false,
        registrationType: 'group',
        minGroupSize: 2,
        maxGroupSize: 4,
        status: 'Open',
        registeredCount: 45,
        maxCapacity: 100,
        representativePhone: '+91 98765 43210',
    },
    {
        id: '2',
        name: 'Grand Cultural Night',
        club: 'Arts & Culture',
        clubId: 'c2',
        description: 'An evening of dance, music, and drama showcasing the diverse talents of our students.',
        rules: '1. Individual or group participation.\n2. Auditions mandatory for stage acts.',
        venue: 'College Main Ground',
        date: '2026-04-20T18:00:00Z',
        deadline: '2026-04-15T23:59:59Z',
        poster: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=800&q=80',
        isClosed: false,
        registrationType: 'individual',
        status: 'Open',
        registeredCount: 120,
        maxCapacity: 500,
        representativePhone: '+91 91234 56789',
    },
    {
        id: '3',
        name: 'Generative AI Workshop',
        club: 'AI & ML Club',
        clubId: 'c3',
        description: 'Hands-on session on building applications using LLMs and modern AI frameworks.',
        rules: '1. Basic Python knowledge required.\n2. Limited seats available.',
        venue: 'Seminar Hall 2',
        date: '2026-03-25T14:30:00Z',
        deadline: '2026-03-22T23:59:59Z',
        poster: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=800&q=80',
        isClosed: false,
        registrationType: 'both',
        status: 'Open',
        registeredCount: 85,
        maxCapacity: 100,
        representativePhone: '+91 88888 77777',
    },
    {
        id: '4',
        name: 'Annual Sports Meet',
        club: 'Sports Club',
        clubId: 'c4',
        description: 'Participate in various track and field events. Let the games begin!',
        rules: '1. Maximum 3 events per student.\n2. College ID card mandatory.',
        venue: 'Sports Complex',
        date: '1026-03-05T08:00:00Z',
        deadline: '2026-03-01T23:59:59Z',
        poster: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=800&q=80',
        isClosed: false,
        registrationType: 'individual',
        status: 'Open',
        registeredCount: 210,
        maxCapacity: 400,
        representativePhone: '+91 77777 66666',
    },
    {
        id: '5',
        name: 'Winter Coding Workshop',
        club: 'Coding Club',
        clubId: 'c1',
        description: 'A week-long intensive workshop on Data Structures and Algorithms held during the winter break.',
        rules: '1. Open to all years.\n2. Certificates will be provided.',
        venue: 'CS Hall A',
        date: '2025-12-20T10:00:00Z',
        deadline: '2025-12-15T23:59:59Z',
        poster: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=800&q=80',
        isClosed: true,
        registrationType: 'individual',
        status: 'Closed',
        registeredCount: 50,
        maxCapacity: 50,
        representativePhone: '+91 98765 43210',
    },
];

export const mockAnnouncements: Announcement[] = [
    {
        id: 'a1',
        title: 'Event Postponed: Tech-Nexus Hackathon',
        content: 'The Coding Club has postponed the Tech-Nexus Hackathon to March 25th due to lab maintenance. Updated schedule will be sent via email.',
        date: '2026-02-16T10:00:00Z',
    },
    {
        id: 'a2',
        title: 'Meeting Cancelled: Robotics Club',
        content: 'The weekly Robotics Club orientation scheduled for tomorrow has been cancelled. Join us next Wednesday at the same time.',
        date: '2026-02-16T08:30:00Z',
    },
    {
        id: 'a3',
        title: 'Venue Change: AI Workshop',
        content: 'Attention! The Gen-AI workshop venue has been shifted from Seminar Hall 2 to the Main Auditorium to accommodate more students.',
        date: '2026-02-15T09:00:00Z',
    },
];

export const mockNotifications: Notification[] = [
    {
        id: 'n1',
        title: 'Hackathon Alert!',
        message: 'The Tech-Nexus Hackathon registration is closing in 3 days.',
        type: 'announcement',
        date: '2026-03-07T09:00:00Z',
        isRead: false,
    },
    {
        id: 'n2',
        title: 'Registration Confirmed',
        message: 'Your registration for Grand Cultural Night has been confirmed.',
        type: 'confirmation',
        date: '2026-02-14T15:30:00Z',
        isRead: true,
    },
];

export const mockRegistrations: Registration[] = [
    {
        id: 'r1',
        eventId: '2',
        event: mockEvents[1],
        studentId: '1',
        registrationDate: '2026-02-14T15:30:00Z',
        status: 'confirmed',
    },
    {
        id: 'r2',
        eventId: '5',
        event: mockEvents[4],
        studentId: '1',
        registrationDate: '2025-12-10T09:00:00Z',
        status: 'confirmed',
    },
];
